/* Hotels */
const SET_LOADING_HOTELS = "SET_LOADING_HOTELS";
const SET_HOTELS = "SET_HOTELS";
const SET_ERROR_HOTELS = "SET_ERROR_HOTELS";

export {
    SET_LOADING_HOTELS,
    SET_HOTELS,
    SET_ERROR_HOTELS,
};