/* Hotels */
const SET_LOADING_HOTELS = "SET_LOADING_HOTELS";
const SET_HOTELS = "SET_HOTELS";
const SET_ERROR_HOTELS = "SET_ERROR_HOTELS";
/* Messages */
const SET_LOADING_MESSAGES = "SET_LOADING_MESSAGES";
const SET_ERROR_MESSAGES = "SET_ERROR_MESSAGES";
const SET_MESSAGES = "SET_MESSAGES";
const SET_MESSAGE_ACTIVE = "SET_MESSAGE_ACTIVE";
const CLEAR_MESSAGE_ACTIVE = "CLEAR_MESSAGE_ACTIVE";

export {
    SET_LOADING_HOTELS,
    SET_HOTELS,
    SET_ERROR_HOTELS,
    SET_LOADING_MESSAGES,
    SET_ERROR_MESSAGES,
    SET_MESSAGES,
    SET_MESSAGE_ACTIVE,
    CLEAR_MESSAGE_ACTIVE,
};